#!/usr/bin/perl
# vi: set ts=4 sw=4 :
#____________________________________________________________________________
#
#   MusicBrainz -- the open internet music database
#
#   Copyright (C) 2000 Robert Kaye
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   This module by Dave Evans, July 2007.
#____________________________________________________________________________

use warnings;
use strict;

use FindBin;
use lib "$FindBin::Bin/../cgi-bin";

use MusicBrainz::Server::RateLimitClient;

@ARGV == 3 or die "Usage: $0 addr port query\n";
my ($addr, $port, $query) = @ARGV;

my $data = MusicBrainz::Server::RateLimitClient->query($query, "${addr}:${port}");
defined($data) or print(STDERR "Failed to get response\n"), exit 1;
print "$data\n";

# eof
