#!/bin/bash

# use topwsip to create a list of IPs to deny (nginx)
# It keeps only those having 10 occurrences of 10 loops, which means IPs
# over 1.5x rate limit for 200 seconds.

./topwsip 2>/dev/null | grep 'ws ip='|awk '{print $8}'|sort -V|uniq -c|sort -nr -k1|awk '{if ($1 > 9) { print $2 }}'|sed 's/ip=//'|sort -V|sed 's/^/deny /;s/$/;/'
